#!/bin/sh

#!/bin/bash

# Create 2nd-level .fsf file for a subject. 

model=$1/
subj=$2


temp_subID=CCK

create_fsf() {

	
sed s/${temp_subID}/${subj}/g /data2/model_3/2nd_level_5/${temp_subID}.gfeat/design.fsf > ${model}/${subj}.fsf 

}

# This is to execute the function
create_fsf $1 $2
# example:
# $1: model_2
# $2: subj_003

